### ISSUE TITLE
翻訳について

### ISSUE THREAD

**Issue by yyoossk** [turtle-insect/Neumann#2]
どうも！
turtle-insectさんのセーブエディタなど大変お世話になっております！
お尋ねしたいのですが、日本人に日本の翻訳云々聞くのもおかしな話ですが、この自作ソフトを多言語翻訳対応のために、ほかの自作ソフトのように言語ファイル対応などはされませんですか？
もしできることでしたら、日本語翻訳したいです！

**Comment by turtle-insect** [comment]
こんにちは

> 多言語対応

https://github.com/turtle-insect/Neumann/blob/master/source/Resource.cpp
昔実現しようとして途中で放置しているみたいですね
機能の実装からになりますが、対応してみますね

**Comment by yyoossk** [comment]
ご対応ありあがとうございます！
楽しみに待ってます！

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/Neumann/commit/10f609a4c90be8b0c813328194b70b4fdbbd57ce

対応しました

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/Neumann/blob/master/romfs/lang/jp.txt

動作確認の為、日本語リソースも作成してしまいました。。。
違和感あれば指摘下さい

**Comment by yyoossk** [comment]
おお
ありがとうございます！
