### ISSUE TITLE
Korean is broken.

### ISSUE THREAD

**Issue by jkh0kr** [turtle-insect/Neumann#3]
PlSharedFontType_Standard             = 0,  ///< Japan, US and Europe
     PlSharedFontType_ChineseSimplified    = 1,  ///< Chinese Simplified
     PlSharedFontType_ExtChineseSimplified = 2,  ///< Extended Chinese Simplified
     PlSharedFontType_ChineseTraditional   = 3,  ///< Chinese Traditional
     PlSharedFontType_KO                   = 4,  ///< Korean (Hangul)
     PlSharedFontType_NintendoExt          = 5,  ///< Nintendo Extended. This font only has the special Nintendo-specific characters, which aren't available with the other fonts.
     PlSharedFontType_Total,                     ///< Total fonts supported by this enum.

https://git.nicholemattera.com/NicholeMattera/Chocolate-Doom-Launcher/src/commit/436aeff7623a8982cbac4058b5b37d4b10c64ccd/Source/Managers/Font.cpp

Please see the code above and patch it.

And Please support Korean language. Added language files.

[ko.txt](https://github.com/turtle-insect/Neumann/files/7274747/ko.txt)

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/Neumann/commit/ea3f83675491fb64a2784936a599b4c3d13a75fd

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/Neumann/releases/tag/0.0.23
